require "zip"

module Exports
  class ReactProjectBuilder
    def initialize(design)
      @design = design
      @libraries = design.component_libraries.to_a
      @jsx = design.last_jsx
    end

    def build
      buffer = Zip::OutputStream.write_buffer do |zip|
        zip.put_next_entry("#{project_name}/package.json")
        zip.write package_json

        zip.put_next_entry("#{project_name}/index.html")
        zip.write index_html

        zip.put_next_entry("#{project_name}/src/App.jsx")
        zip.write app_jsx

        zip.put_next_entry("#{project_name}/src/main.jsx")
        zip.write main_jsx

        zip.put_next_entry("#{project_name}/src/index.css")
        zip.write index_css

        # Include component library code
        write_component_files(zip) if @libraries.any?

        zip.put_next_entry("#{project_name}/README.md")
        zip.write readme
      end

      buffer.string
    end

    private

    def project_name
      @design.name&.parameterize.presence || "design-export"
    end

    def package_json
      {
        name: project_name,
        version: "1.0.0",
        private: true,
        type: "module",
        scripts: {
          dev: "vite",
          build: "vite build",
          preview: "vite preview"
        },
        dependencies: {
          react: "^18.2.0",
          "react-dom": "^18.2.0"
        },
        devDependencies: {
          "@vitejs/plugin-react": "^4.0.0",
          vite: "^5.0.0"
        }
      }.to_json
    end

    def index_html
      <<~HTML
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <title>#{@design.name}</title>
        </head>
        <body>
          <div id="root"></div>
          <script type="module" src="/src/main.jsx"></script>
        </body>
        </html>
      HTML
    end

    def app_jsx
      component_imports = collect_component_names.map { |name|
        "import { #{name} } from './components/#{name}';"
      }.join("\n")

      <<~JSX
        #{component_imports}

        export default function App() {
          return (
            #{@jsx}
          );
        }
      JSX
    end

    def main_jsx
      <<~JSX
        import React from 'react';
        import ReactDOM from 'react-dom/client';
        import App from './App';
        import './index.css';

        ReactDOM.createRoot(document.getElementById('root')).render(
          <React.StrictMode>
            <App />
          </React.StrictMode>
        );
      JSX
    end

    def index_css
      css_parts = []
      @libraries.each do |lib|
        lib.component_sets.each do |cs|
          variant = cs.default_variant
          css_parts << variant.css_code if variant&.css_code.present?
        end
        lib.components.each do |c|
          css_parts << c.css_code if c.css_code.present?
        end
      end
      css_parts.join("\n\n")
    end

    def write_component_files(zip)
      @libraries.each do |lib|
        lib.component_sets.reject(&:vector?).each do |cs|
          variant = cs.default_variant
          next unless variant&.react_code.present?
          name = component_name_for(cs.name)
          zip.put_next_entry("#{project_name}/src/components/#{name}.jsx")
          zip.write wrap_component(name, variant.react_code)
        end

        lib.components.reject(&:vector?).each do |c|
          next unless c.react_code.present?
          name = component_name_for(c.name)
          zip.put_next_entry("#{project_name}/src/components/#{name}.jsx")
          zip.write wrap_component(name, c.react_code)
        end
      end
    end

    def wrap_component(name, code)
      <<~JSX
        import React from 'react';

        #{code}

        export { #{name} };
      JSX
    end

    def collect_component_names
      names = []
      return names unless @jsx
      @jsx.scan(/<(\w+)/).flatten.uniq.reject { |n| n =~ /^[a-z]/ }
    end

    def component_name_for(name)
      name.gsub(/[^a-zA-Z0-9]/, "")
    end

    def readme
      <<~MD
        # #{@design.name}

        Generated by Design-GPT.

        ## Getting Started

        ```bash
        npm install
        npm run dev
        ```
      MD
    end
  end
end
