source "https://rubygems.org"

ruby "3.3.9"

gem "rails", "~> 8.0.2", ">= 8.0.2.1"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"
gem "bootsnap", require: false
gem "kamal", require: false
gem "thruster", require: false
gem "http"
gem "ruby-openai"
gem "foreman"
gem "auth0"
gem "jwt"
gem "faraday"
gem "dotenv"
gem "rack-cors"
gem "ferrum"
gem "chunky_png"
gem "rubyzip", require: "zip"
gem "rspec-rails"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "webmock"
end
